//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ims_error_handle
    {
        public int id { get; set; }
        public string error_code { get; set; }
        public string description { get; set; }
        public string solution { get; set; }
        public string video_path { get; set; }
    }
}
